CREATE TABLE IF NOT EXISTS stock_master (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    code VARCHAR(16) NOT NULL COMMENT '股票代码',
    name VARCHAR(64) NOT NULL COMMENT '股票名称',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股票主数据表';


CREATE TABLE IF NOT EXISTS stock_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    stock_code VARCHAR(16) NOT NULL COMMENT '股票代码',
    open DECIMAL(16,4) NOT NULL COMMENT '开盘价',
    close DECIMAL(16,4) NOT NULL COMMENT '收盘价',
    high DECIMAL(16,4) NOT NULL COMMENT '最高价',
    low DECIMAL(16,4) NOT NULL COMMENT '最低价',
    vol BIGINT UNSIGNED NOT NULL COMMENT '成交量',
    amount DECIMAL(20,4) NOT NULL COMMENT '成交额',
    trade_date DATE NOT NULL COMMENT '交易日',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_stock_daily_stock_code_trade_date (stock_code, trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股票日线数据表';
